    // let category = [
        //     "Phone",
        //     "PC",
        //     "Table",
        //     "TV",
        //     "Laptop",
        //     "Watch",
        //     "Monitor",
        //     "Camera",
        // ]
        // let productList = [
        //     {
        //         id: Date.now() * Math.random(),
        //         name: "Laptop Asus",
        //         price: 25000000,
        //         image: "./asset/lap1.jpg",
        //         category: category[4],
        //         quantity: 1,
        //     },
        //     {
        //         id: Date.now() * Math.random(),
        //         name: "Laptop Lenovo 1",
        //         price: 21000000,
        //         image: "./asset/lap2.png",
        //         category: category[4],
        //         quantity: 1,
        //     },
        //     {
        //         id: Date.now() * Math.random(),
        //         name: "Laptop Lenovo 2",
        //         price: 15000000,
        //         image: "./asset/lap3.png",
        //         category: category[4],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Laptop Apple",
        //         price: 35000000,
        //         image: "./asset/lap4.jpg",
        //         category: category[4],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Laptop MSI",
        //         price: 25000000,
        //         image: "./asset/lap5.jpg",
        //         quantity: 1,
        //         category: category[4],
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Monitor Coocaa",
        //         price: 5000000,
        //         image: "./asset/monitor1.png",
        //         quantity: 1,
        //         category: category[6],
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Monitor Samsung",
        //         price: 7000000,
        //         image: "./asset/monitor2.jpg",
        //         quantity: 1,
        //         category: category[6],
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Apple Iphone",
        //         price: 25000000,
        //         image: "./asset/phone1.png",
        //         category: category[0],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Samsung ZFold Phone",
        //         price: 31000000,
        //         image: "./asset/phone2.jpg",
        //         category: category[0],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Redmi Phone ",
        //         price: 7500000,
        //         image: "./asset/phone3.jpg",
        //         category: category[0],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Samsung Ultra Phone",
        //         price: 26000000,
        //         image: "./asset/phone4.png",
        //         category: category[0],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Samsung Flip Phone",
        //         price: 15000000,
        //         image: "./asset/phone5.jpg",
        //         category: category[0],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Tivi Samsung",
        //         price: 28000000,
        //         image: "./asset/tv1.jpg",
        //         category: category[3],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Tivi Xiaomi 1",
        //         price: 11000000,
        //         image: "./asset/tv2.png",
        //         category: category[3],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Tivi Xiaomi 2",
        //         price: 16000000,
        //         image: "./asset/tv3.png",
        //         category: category[3],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Apple Watch",
        //         price: 15000000,
        //         image: "./asset/watch1.jpg",
        //         category: category[5],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Samsung Watch 1",
        //         price: 8000000,
        //         image: "./asset/watch2.png",
        //         category: category[5],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Xiaomi Watch",
        //         price: 3000000,
        //         image: "./asset/watch3.png",
        //         category: category[5],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Huawei Watch",
        //         price: 6000000,
        //         image: "./asset/watch4.png",
        //         category: category[5],
        //         quantity: 1,
        //     }, {
        //         id: Date.now() * Math.random(),
        //         name: "Samsung Watch 2",
        //         price: 9000000,
        //         image: "./asset/watch5.jpg",
        //         category: category[5],
        //         quantity: 1,
        //     }
        // ]